[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "B", "UP", "ANN", "COM", "DTZ", "PIE"]
ignore = ["ANN101", "ANN102"]
src = ["packages"]

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
strict_optional = true

[tool.pytest.ini_options]
testpaths = ["packages/elementals/tests"]
addopts = "-q"
