Echo:
  class: EchoFunction
  description: Echo input params
  duration: short
  enabled: true
  module: elementals.examples.echo
  name: Echo
  resource_type: cpu
  role: business_action
  sync: sync
Multiply:
  class: MultiplyFunction
  description: Multiply two numbers and return product
  duration: short
  enabled: true
  module: elementals.examples.multiply
  name: Multiply
  resource_type: cpu
  role: business_action
  sync: sync
Sum:
  class: SumFunction
  description: Sum two numbers
  duration: short
  enabled: true
  module: elementals.examples.sum
  name: Sum
  resource_type: cpu
  role: business_action
  sync: sync
