name: CI (nox)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Tests (nox)
        run: nox -s tests-${{ matrix.python-version }}

      - name: Lint & Type (nox, only on 3.12)
        if: matrix.python-version == '3.12'
        run: |
          nox -s lint
          nox -s type

      - name: Build packages (nox, only on 3.12)
        if: matrix.python-version == '3.12'
        run: nox -s build_all
